In [3]:
import numpy as np
from scaler import Scaler
from scipy import sparse

In [18]:
a = np.random.rand(10,10)
b= np.random.rand(100,10)

In [19]:
a.dot(b.transpose())

array([[3.12466395, 3.79668321, 2.34445451, 2.76517241, 2.78900101,
        3.92261828, 2.46150479, 2.84197093, 2.41776009, 2.21105652,
        2.56956729, 2.9122854 , 2.22624139, 3.90657555, 2.31262298,
        3.3038538 , 2.51325068, 2.41714525, 2.32061925, 2.84870476,
        3.41706259, 3.77118831, 3.60115135, 2.69502373, 1.98136963,
        2.68288031, 3.18497649, 3.1391253 , 2.40477139, 2.98290302,
        1.89569317, 2.61636984, 4.36203162, 3.60024775, 2.82963232,
        2.47261169, 2.00340913, 2.38518373, 2.59337611, 3.48112587,
        2.80062686, 3.41579577, 3.36031575, 2.59799091, 2.28504843,
        3.13664286, 2.2392419 , 2.97249767, 2.77280754, 2.71037672,
        2.1894298 , 2.37150231, 3.02060338, 2.4524027 , 3.79440069,
        2.41242617, 2.72495339, 2.61111957, 2.06850596, 2.75709211,
        2.840497  , 1.95616586, 2.66756455, 2.44729347, 1.95935562,
        3.46845653, 3.65109192, 3.33904535, 2.72727115, 2.02551964,
        2.25465581, 2.87736582, 3.00153649, 2.39

In [26]:
a = sparse.csr_matrix(a)
b = sparse.csr_matrix(b.transpose())

In [27]:
a.dot(b).toarray()

array([[3.12466395, 3.79668321, 2.34445451, 2.76517241, 2.78900101,
        3.92261828, 2.46150479, 2.84197093, 2.41776009, 2.21105652,
        2.56956729, 2.9122854 , 2.22624139, 3.90657555, 2.31262298,
        3.3038538 , 2.51325068, 2.41714525, 2.32061925, 2.84870476,
        3.41706259, 3.77118831, 3.60115135, 2.69502373, 1.98136963,
        2.68288031, 3.18497649, 3.1391253 , 2.40477139, 2.98290302,
        1.89569317, 2.61636984, 4.36203162, 3.60024775, 2.82963232,
        2.47261169, 2.00340913, 2.38518373, 2.59337611, 3.48112587,
        2.80062686, 3.41579577, 3.36031575, 2.59799091, 2.28504843,
        3.13664286, 2.2392419 , 2.97249767, 2.77280754, 2.71037672,
        2.1894298 , 2.37150231, 3.02060338, 2.4524027 , 3.79440069,
        2.41242617, 2.72495339, 2.61111957, 2.06850596, 2.75709211,
        2.840497  , 1.95616586, 2.66756455, 2.44729347, 1.95935562,
        3.46845653, 3.65109192, 3.33904535, 2.72727115, 2.02551964,
        2.25465581, 2.87736582, 3.00153649, 2.39

In [6]:
b.dot(a.transpose())

array([[2.73384294, 2.96326711, 3.26688775, ..., 2.66017036, 2.89305712,
        3.3732489 ],
       [3.39519175, 3.59393385, 3.9008798 , ..., 3.31613447, 3.66630429,
        3.86555803],
       [2.22529944, 2.63943493, 2.81235112, ..., 2.14265467, 2.01127842,
        2.99500557],
       ...,
       [3.4655298 , 3.73824002, 3.81307554, ..., 3.26012702, 3.73258842,
        3.74146969],
       [2.12231382, 2.32642783, 2.4999813 , ..., 2.45595422, 2.53834701,
        2.49764783],
       [2.06760255, 2.09945088, 2.04848474, ..., 1.89366181, 2.46292034,
        2.46495227]])